### ISSUE TITLE
Launch interactive mode only if no arguments are passed to the binary

### ISSUE THREAD

**Issue by MarcVillain** [MarcVillain/acdc-toolkit#7]
Examples:
```acdc``` Run the toolkit in interactive mode.
```acdc get csharp-tp14``` Run the command directly.

**Comment by alex-van-vliet** [comment]
Done in 9584b59

**Comment by MarcVillain** [comment]
@alex-van-vliet You added handling for this feature while launching the toolkit directly but forgot to update the alias execution in the install script.
Maybe this can be the opportunity to move the alias code into a specific file in the toolkit to make it easier to update.

Now, the alias is:
```
alias acdc="cd $acdc_local_folder/toolkit
    pipenv run ./toolkit.py
    if [ \"\$?\" -eq 1 ]; then
        pipenv install
        pipenv run ./toolkit.py
    fi"
```

Maybe it could simply run a shell script in toolkit instead:
```
alias acdc="./$acdc_local_folder/run_toolkit.sh"
```

**Comment by MarcVillain** [comment]
Requested feature done in 265f88e
